# Checks to see if a new release has happened. If so, it stands up a FusionAuth instance and downloads the themes.
name: updatethemes
on: 
  pull_request:
  # run once a day
  schedule:
    - cron: '31 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updatethemes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      version: 1.45.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Download and install FusionAuth
        run: |
          curl -o $version.deb https://files.fusionauth.io/products/fusionauth/$version/fusionauth-app_$version-1_all.deb  
          dpkg -i $version.deb
          systemctl start fusionauth-app
          sleep 10
          curl -o - http://localhost:9011
        shell: bash
