# Checks to see if a new release has happened. If so, it stands up a FusionAuth instance and downloads the themes.
name: updatethemes
on: 
  pull_request:
  # run once a day
  schedule:
    - cron: '31 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updatethemes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: fusionauth
          POSTGRES_USER: fusionauth
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      version: 1.45.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Download and install FusionAuth
        run: |
          curl -o $version.zip https://files.fusionauth.io/products/fusionauth/$version/fusionauth-app-$version.zip
          mkdir fusionauth && cd fusionauth
          unzip ../$version.zip
          ./bin/startup.sh
          
          sleep 30
          #PGPASSWORD=fusionauth psql -h localhost -U fusionauth -c "select 1"
          tail -20 /home/runner/work/fusionauth-theme-history/fusionauth-theme-history/fusionauth/logs/fusionauth-app.log
          curl -o - 'http://localhost:9011/'
        shell: bash
